server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          #uri: http://localhost:8081
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: user-service
          #uri: http://localhost:8082
          uri: http://user-service:8082
          predicates:
            - Path=/users/**

        - id: booking-service
         # uri: http://localhost:8083
          uri: http://booking-service:8083
          predicates:
            - Path=/bookings/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: ZmluYW5jZS1hcHAtamF3dC1zZWNyZXQtbXlzaWduYXR1cmU=